### ISSUE TITLE
CMake: command not found

### ISSUE THREAD

**Issue by rafa-martin** [eyllanesc/69108420#1]
Hello i forked your repo to test github actions with Qt5, but throw this error in the step: "Configure CMake":

![image](https://user-images.githubusercontent.com/23015374/163835156-b533caf0-5bfb-4eb3-9d63-75551435c0f4.png)

I seems that cmake is not installed.
Any idea to solve it. Thanks in advance :D

**Comment by cagnulein** [comment]
same here @TheBerbat did you fix it?

**Comment by rafa-martin** [comment]
I'm still trying @cagnulein

**Comment by rafa-martin** [comment]
I finaly solved this issue :D and created pull-request to add it in this repository.

**Comment by cagnulein** [comment]
This is mine https://github.com/cagnulein/qdomyos-zwift/commit/fc1c246e8cce20e09eac8cd70fdf83b2cbb9a5e5
